"""Add missing tables and columns

Revision ID: 7cdd2c3f0773
Revises: b8c1d2e3f4a5
Create Date: 2026-04-19 06:00:54.676277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cdd2c3f0773'
down_revision: Union[str, Sequence[str], None] = 'b8c1d2e3f4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('newspapers', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billing_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('max_workers', sa.Integer(), nullable=True),
    sa.Column('max_customers', sa.Integer(), nullable=True),
    sa.Column('price_monthly', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('billing_cycle', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('announcements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('target_audience', sa.String(length=50), nullable=True),
    sa.Column('target_agency_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['target_agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('backup_name', sa.String(length=255), nullable=False),
    sa.Column('backup_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('gdrive_file_id', sa.String(length=255), nullable=True),
    sa.Column('gdrive_web_link', sa.String(length=512), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker_daily_stock',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('newspaper_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('taken', sa.Integer(), nullable=True),
    sa.Column('returned', sa.Integer(), nullable=True),
    sa.Column('amount_given', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['newspaper_id'], ['newspapers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agencies', sa.Column('billing_plan_id', sa.Uuid(), nullable=True))
    op.add_column('agencies', sa.Column('gdrive_refresh_token', sa.Text(), nullable=True))
    op.add_column('agencies', sa.Column('gdrive_folder_id', sa.String(length=255), nullable=True))
    op.add_column('agencies', sa.Column('gdrive_connected_at', sa.DateTime(), nullable=True))
    op.add_column('agencies', sa.Column('gdrive_oauth_state', sa.String(length=512), nullable=True))
    op.create_foreign_key(None, 'agencies', 'billing_plans', ['billing_plan_id'], ['id'])
    op.drop_column('daily_stock', 'sold')
    op.add_column('newspapers', sa.Column('paper_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('newspapers', 'paper_type')
    op.add_column('daily_stock', sa.Column('sold', sa.INTEGER(), sa.Computed('(taken - returned)', persisted=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'agencies', type_='foreignkey')
    op.drop_column('agencies', 'gdrive_oauth_state')
    op.drop_column('agencies', 'gdrive_connected_at')
    op.drop_column('agencies', 'gdrive_folder_id')
    op.drop_column('agencies', 'gdrive_refresh_token')
    op.drop_column('agencies', 'billing_plan_id')
    op.drop_table('worker_daily_stock')
    op.drop_table('backups')
    op.drop_table('announcements')
    op.drop_table('billing_plans')
    op.drop_table('agency_templates')
    # ### end Alembic commands ###
